### PR TITLE
ember-cli 1.13.8

### PR DESCRIPTION
**Pull request by Dhaulagiri**
* Update to ember-cli 1.13.8/ember 1.13.9
* Upgrade other deps
* Add version number to package.json
* Add ember observer badge

### CODE REVIEW

**Comment by captmorgan** [comment]
awesome.  @Robdel12  can this get merged?

**Comment by Robdel12** [comment]
Ah yes! I forgot about this. I can merge this, but we're not interested in keeping this repo. Would anyone like to become the new champion for this?

**Comment by Dhaulagiri** [comment]
I would be interested @Robdel12

**Comment by cowboyd** [comment]
@Dhaulagiri Take good care of it! Can you send me your username on NPM so we can transfer the package as well?

**Comment by cowboyd** [comment]
Also @Dhaulagiri, you'll have to delete your own fork before we can transfer ownership.

**Comment by Dhaulagiri** [comment]
Done @cowboyd.  My npm username is [dhaulagiri](https://www.npmjs.com/~dhaulagiri) as well.

**Comment by cowboyd** [comment]
Done and done!

**Pull request merged**
